# Generated by Django 4.1.1 on 2022-12-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('passageID', models.AutoField(primary_key=True, serialize=False)),
                ('passage', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'passage',
            },
        ),
    ]
